---
- name: configure gentoo
  include_tasks: configure-gentoo.yml
  when: ansible_os_family == 'Gentoo'

- name: Get default sync period
  include_tasks: get-default-sync-period.yml

- name: update cache Debian
  include_tasks: package-update-debian.yml
  when: ansible_os_family == 'Debian'

- name: update cache Gentoo
  include_tasks: package-update-gentoo.yml
  when: ansible_os_family == 'Gentoo'

- name: install packages Debian
  include_tasks: package-install-debian.yml
  when: ansible_os_family == 'Debian'

- name: install packages Gentoo
  include_tasks: package-install-gentoo.yml
  when: ansible_os_family == 'Gentoo'
