---
- name: check if timestamp file exist
  stat:
    path: "/var/lib/apt/lists"
  register: apt_timestamp

- name: Get last sync date
  command: stat -c %Y /var/lib/apt/lists
  register: apt_update
  changed_when: False
  failed_when: apt_update.rc != 0
  when:
    - ansible_os_family == 'Debian'
    - apt_timestamp.stat.exist is defined and apt_timestamp.stat.exist is true
    - not ansible_check_mode

- debug:
    msg:
      - "Package cache db seems not initialized"
      - "path:"
      - "/var/lib/apt/lists"
      - "stat:"
      - "{{ apt_timestamp.stat }}"
  when:
    - apt_timestamp.stat is defined and apt_timestamp.stat.exists is false

- name: Date debug Debian non-mirror
  debug:
    msg:
      - "To update apt_update should be older (<) than pkg_timestamp"
      - "                     |  timestamp   | date"
      - "pkg_timestamp        |  {{ pkg_timestamp.stdout }}  | {{ pkg_sync_period }}"
      - "apt_update           |  {{ apt_update.stdout }} "
  when:
    - ansible_os_family == 'Debian'
    - "'pkg_mirror' not in group_names"
    - apt_update.stdout is defined and apt_update.stdout | int() <= pkg_timestamp.stdout | int()
    - apt_timestamp.stat is defined and apt_timestamp.stat.exists is true
    - not ansible_check_mode

- name: Date debug Debian mirror
  debug:
    msg:
      - "To update apt_update_ should be older (<) than pkg_timestamp_mirror"
      - "                     |  timestamp   | date"
      - "pkg_timestamp_mirror |  {{ pkg_timestamp_mirror.stdout }}  | {{ pkg_sync_period }}"
      - "apt_update           |  {{ apt_update.stdout }} "
  when:
    - ansible_os_family == 'Debian'
    - "'pkg_mirror' in group_names"
    - apt_update.stdout is defined and apt_update.stdout | int() <= pkg_timestamp.stdout | int()
    - apt_timestamp.stat is defined and apt_timestamp.stat.exists is true
    - not ansible_check_mode

- name: Apt sync non mirror
  command: apt update
  when:
    - ansible_os_family == 'Debian'
    - "'pkg_mirror' not in group_names"
    - pkg_timestamp.stdout is defined
    - (apt_update.stdout is defined and apt_update.stdout | int() <= pkg_timestamp.stdout | int()) or
      apt_timestamp.stat is defined and apt_timestamp.stat.exists is false
    - not ansible_check_mode

- name: Apt sync mirror
  command: apt update
  when:
    - ansible_os_family == 'Debian'
    - "'pkg_mirror' in group_names"
    - pkg_timestamp_mirror.stdout is defined
    - (apt_update.stdout is defined and apt_update.stdout | int() <= pkg_timestamp.stdout | int()) or
      apt_timestamp.stat is defined and apt_timestamp.stat.exists is false
    - not ansible_check_mode
