---
  - name: check equery command
    ansible.builtin.raw: which equery
    register: cmd_which_equery
    changed_when: false
    failed_when: false
    when:
      - ansible_os_family == 'Gentoo'

  - name: install gentoolkit if needed
    command: emerge -v app-portage/gentoolkit
    when:
      - ansible_os_family == 'Gentoo'
      - cmd_which_equery.rc != 0

  - name: install packages Gentoo package_fact deps
    community.general.portage:
      package: "{{ item }}"
      state: present
      update: yes
    loop:
      - app-portage/portage-utils
      - app-portage/gentoolkit
    when:
      - ansible_os_family == 'Gentoo'

  - name: Check package are install-able Gentoo
    command: emerge -pv "{{ item.value.name }}"
    loop: "{{ pkg_install | dict2items }}"
    register: cmd_emerge_pretend
    changed_when: False
    failed_when: cmd_emerge_pretend.rc != 0
    when:
      - ansible_os_family == 'Gentoo'
      - item.value.name is defined

  - name: install packages Gentoo
    community.general.portage:
      package: "{{ item.value.name }}"
      state: present
      update: yes
      changed_use: yes
    loop: "{{ pkg_install | dict2items }}"
    when:
      - ansible_os_family == 'Gentoo'
      - item.value.name is defined
