---
- name: Get last sync date
  command: stat -c %Y /var/lib/apt/lists
  register: apt_update_date
  changed_when: False
  failed_when: apt_update_date.rc != 0
  when:
    - ansible_os_family == 'Debian'
    - not ansible_check_mode

# @TODO Add case for non initialized db
- name: Date debug Debian non-mirror
  debug:
    msg:
      - "To update apt_update_date should be older (<) than pkg_timestamp"
      - "                     |  timestamp   | date"
      - "pkg_timestamp        |  {{ pkg_timestamp.stdout }}  | {{ pkg_sync_period }}"
      - "apt_update_date      |  {{ apt_update_date.stdout }} "
  when:
    - ansible_os_family == 'Debian'
    - "'pkg_mirror' not in group_names"
    - not ansible_check_mode

- name: Date debug Debian mirror
  debug:
    msg:
      - "To update apt_update_date_ should be older (<) than pkg_timestamp_mirror"
      - "                     |  timestamp   | date"
      - "pkg_timestamp_mirror |  {{ pkg_timestamp_mirror.stdout }}  | {{ pkg_sync_period }}"
      - "apt_update_date      |  {{ apt_update_date.stdout }} "
  when:
    - ansible_os_family == 'Debian'
    - "'pkg_mirror' in group_names"
    - not ansible_check_mode

- name: Apt sync non mirror
  command: apt update
  when:
    - ansible_os_family == 'Debian'
    - pkg_timestamp.stdout is defined
    - apt_update_date.stdout is defined and apt_update_date.stdout | int() <= pkg_timestamp.stdout | int()
    - "'pkg_mirror' not in group_names"
    - not ansible_check_mode

- name: Apt sync mirror
  command: apt update
  when:
    - ansible_os_family == 'Debian'
    - pkg_timestamp_mirror.stdout is defined
    - (apt_update_date.stdout is defined and apt_update_date.stdout | int() <= pkg_timestamp_mirror.stdout | int())
    - "'pkg_mirror' in group_names"
    - not ansible_check_mode
